[package]
name = "solana-game-template"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_game_template"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "proto-interface/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = "0.32.1"
rand = { version = "0.8", features = ["std"] }
getrandom = { version = "0.2.10", features = ["custom"] }
proto-interface = { path = "../../proto-interface" }
bytemuck = { workspace = true }

[dev-dependencies]
anchor-client = "0.32.1"
tokio = { version = "1", features = ["full"] }
bs58 = "0.4.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }
