[package]
name = "examples"
version = "0.1.0"
edition = "2021"


[dependencies]
sdk = { path = "../sdk" }
proto-interface = { path = "../proto-interface" }
tokio = { workspace = true }
prost = { workspace = true }
tokio-util = { workspace = true }
futures-util = { workspace = true }
arrayvec = { workspace = true }
dashmap = { workspace = true }
anyhow = { workspace = true }
anchor-client = { workspace = true }
anchor-lang = { workspace = true }
rand = { version = "0.8" , default-features = false}
