[package]
name = "examples"
version = "0.1.0"
edition = "2021"


[dependencies]
sdk = { path = "../sdk" }
solana-game-template ={ path = "../programs/solana-game-template"}
proto-interface = { path = "../proto-interface" }
tokio = { version = "1", features = ["full"] }
prost = "0.12"
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", features = ["sink"] }
arrayvec = { workspace = true }
dashmap = { workspace = true }
anyhow = { workspace = true }
anchor-client = { workspace = true }
anchor-lang = { workspace = true }
rand = { workspace = true }
